#############################################################################
# Makefile for building: netsharer
# Generated by qmake (2.01a) (Qt 4.2.3) on: ?? ?? 9 10:47:49 2007
# Project:  netsharer.pro
# Template: app
# Command: /usr/lib/qt4/bin/qmake-qt4 -unix -o Makefile netsharer.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
LEX           = flex
YACC          = yacc
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -g -march=i386 -mcpu=i686 -Wall -W -D_REENTRANT  $(DEFINES)
CXXFLAGS      = -pipe -O2 -g -march=i386 -mcpu=i686 -Wall -W -D_REENTRANT  $(DEFINES)
LEXFLAGS      = 
YACCFLAGS     = -d
INCPATH       = -I../../../../lib/qt4/mkspecs/linux-g++ -I. -I../../../../include/QtCore -I../../../../include/QtCore -I../../../../include/QtNetwork -I../../../../include/QtNetwork -I../../../../include/QtGui -I../../../../include/QtGui -I../../../../include -I. -Isrc -I. -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)   -lQtGui -lQtNetwork -lQtCore -lpthread
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/qt4/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/main.cpp \
		src/netsharer.cpp moc_netsharer.cpp \
		qrc_netsharer.cpp
OBJECTS       = main.o \
		netsharer.o \
		moc_netsharer.o \
		qrc_netsharer.o
DIST          = ../../../../share/qt4/mkspecs/common/unix.conf \
		../../../../lib/qt4/mkspecs/common/g++-multilib.conf \
		../../../../lib/qt4/mkspecs/common/linux.conf \
		../../../../share/qt4/mkspecs/features/qt_functions.prf \
		../../../../share/qt4/mkspecs/features/qt_config.prf \
		../../../../share/qt4/mkspecs/features/exclusive_builds.prf \
		../../../../share/qt4/mkspecs/features/default_pre.prf \
		../../../../share/qt4/mkspecs/features/release.prf \
		../../../../share/qt4/mkspecs/features/default_post.prf \
		../../../../share/qt4/mkspecs/features/warn_on.prf \
		../../../../share/qt4/mkspecs/features/qt.prf \
		../../../../share/qt4/mkspecs/features/unix/thread.prf \
		../../../../share/qt4/mkspecs/features/moc.prf \
		../../../../share/qt4/mkspecs/features/resources.prf \
		../../../../share/qt4/mkspecs/features/uic.prf \
		netsharer.pro
QMAKE_TARGET  = netsharer
DESTDIR       = 
TARGET        = netsharer

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_addmapdialog.h ui_netsharer.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: netsharer.pro  ../../../../lib/qt4/mkspecs/linux-g++/qmake.conf ../../../../share/qt4/mkspecs/common/unix.conf \
		../../../../lib/qt4/mkspecs/common/g++-multilib.conf \
		../../../../lib/qt4/mkspecs/common/linux.conf \
		../../../../share/qt4/mkspecs/features/qt_functions.prf \
		../../../../share/qt4/mkspecs/features/qt_config.prf \
		../../../../share/qt4/mkspecs/features/exclusive_builds.prf \
		../../../../share/qt4/mkspecs/features/default_pre.prf \
		../../../../share/qt4/mkspecs/features/release.prf \
		../../../../share/qt4/mkspecs/features/default_post.prf \
		../../../../share/qt4/mkspecs/features/warn_on.prf \
		../../../../share/qt4/mkspecs/features/qt.prf \
		../../../../share/qt4/mkspecs/features/unix/thread.prf \
		../../../../share/qt4/mkspecs/features/moc.prf \
		../../../../share/qt4/mkspecs/features/resources.prf \
		../../../../share/qt4/mkspecs/features/uic.prf
	$(QMAKE) -unix -o Makefile netsharer.pro
../../../../share/qt4/mkspecs/common/unix.conf:
../../../../lib/qt4/mkspecs/common/g++-multilib.conf:
../../../../lib/qt4/mkspecs/common/linux.conf:
../../../../share/qt4/mkspecs/features/qt_functions.prf:
../../../../share/qt4/mkspecs/features/qt_config.prf:
../../../../share/qt4/mkspecs/features/exclusive_builds.prf:
../../../../share/qt4/mkspecs/features/default_pre.prf:
../../../../share/qt4/mkspecs/features/release.prf:
../../../../share/qt4/mkspecs/features/default_post.prf:
../../../../share/qt4/mkspecs/features/warn_on.prf:
../../../../share/qt4/mkspecs/features/qt.prf:
../../../../share/qt4/mkspecs/features/unix/thread.prf:
../../../../share/qt4/mkspecs/features/moc.prf:
../../../../share/qt4/mkspecs/features/resources.prf:
../../../../share/qt4/mkspecs/features/uic.prf:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile netsharer.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/netsharer1.0.0 || $(MKDIR) .tmp/netsharer1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/netsharer1.0.0/ && $(COPY_FILE) --parents src/netsharer.h .tmp/netsharer1.0.0/ && $(COPY_FILE) --parents netsharer.qrc .tmp/netsharer1.0.0/ && $(COPY_FILE) --parents src/main.cpp src/netsharer.cpp .tmp/netsharer1.0.0/ && $(COPY_FILE) --parents ui/addmapdialog.ui ui/netsharer.ui .tmp/netsharer1.0.0/ && (cd `dirname .tmp/netsharer1.0.0` && $(TAR) netsharer1.0.0.tar netsharer1.0.0 && $(COMPRESS) netsharer1.0.0.tar) && $(MOVE) `dirname .tmp/netsharer1.0.0`/netsharer1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/netsharer1.0.0


yaccclean:
lexclean:
clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


/usr/lib/qt4/bin/moc:
	(cd $(QTDIR)/src/tools/moc && $(MAKE))

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_netsharer.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_netsharer.cpp
moc_netsharer.cpp: ui_netsharer.h \
		ui_addmapdialog.h \
		src/netsharer.h \
		../../../../lib/qt4/bin/moc
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) src/netsharer.h -o moc_netsharer.cpp

compiler_rcc_make_all: qrc_netsharer.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_netsharer.cpp
qrc_netsharer.cpp: netsharer.qrc \
		../../../../lib/qt4/bin/rcc \
		images/icon.png
	/usr/lib/qt4/bin/rcc -name netsharer netsharer.qrc -o qrc_netsharer.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_addmapdialog.h ui_netsharer.h
compiler_uic_clean:
	-$(DEL_FILE) ui_addmapdialog.h ui_netsharer.h
ui_addmapdialog.h: ui/addmapdialog.ui
	/usr/lib/qt4/bin/uic ui/addmapdialog.ui -o ui_addmapdialog.h

ui_netsharer.h: ui/netsharer.ui
	/usr/lib/qt4/bin/uic ui/netsharer.ui -o ui_netsharer.h

compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_image_collection_clean compiler_moc_source_clean compiler_uic_clean 

####### Compile

main.o: src/main.cpp src/netsharer.h \
		ui_netsharer.h \
		ui_addmapdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

netsharer.o: src/netsharer.cpp src/netsharer.h \
		ui_netsharer.h \
		ui_addmapdialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o netsharer.o src/netsharer.cpp

moc_netsharer.o: moc_netsharer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_netsharer.o moc_netsharer.cpp

qrc_netsharer.o: qrc_netsharer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_netsharer.o qrc_netsharer.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

