######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 9 10:47:09 2007
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . src ui
INCLUDEPATH += . src

# Input
HEADERS += src/netsharer.h
FORMS += ui/addmapdialog.ui ui/netsharer.ui
SOURCES += src/main.cpp src/netsharer.cpp
RESOURCES += netsharer.qrc
QT += network
